
services:
  registry:
    image: registry:2
    container_name: private_registry
    ports:
      - "5000:5000"
    environment:
      - REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin=["http://localhost:8081"]
      - REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods=["HEAD", "GET", "OPTIONS", "DELETE"]
      - REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials=["true"]
    networks:
      - registry_network

  registry-ui:
    image: joxit/docker-registry-ui
    container_name: registry_ui
    ports:
      - "8081:80"
    environment:
      - REGISTRY_TITLE=SUPMIT Docker Registry
      - REGISTRY_URL=http://registry:5000
    depends_on:
      - registry
    networks:
      - registry_network

networks:
  registry_network:

